# Generated by Django 5.2.6 on 2026-08-21 16:05

import django.db.models.deletion
import live.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cbt', '0002_multi_answer_questions'),
        ('core', '0003_school_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=150)),
                ('pin', models.CharField(db_index=True, max_length=6)),
                ('status', models.CharField(choices=[('lobby', 'Lobby'), ('question', 'Question live'), ('reveal', 'Revealing answer'), ('ended', 'Ended')], db_index=True, default='lobby', max_length=10)),
                ('question_ids', models.JSONField(blank=True, default=list)),
                ('current_index', models.IntegerField(default=-1)),
                ('question_started_at', models.DateTimeField(blank=True, null=True)),
                ('seconds_per_question', models.PositiveSmallIntegerField(default=20)),
                ('points_base', models.PositiveIntegerField(default=1000)),
                ('speed_bonus', models.BooleanField(default=True, help_text='Award more points for faster correct answers.')),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='live_games', to='cbt.questionbank')),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosted_games', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.school')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GamePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20)),
                ('token', models.CharField(default=live.models.generate_token, max_length=32, unique=True)),
                ('score', models.IntegerField(default=0)),
                ('streak', models.IntegerField(default=0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='live.gamesession')),
            ],
            options={
                'ordering': ['-score', 'joined_at'],
            },
        ),
        migrations.CreateModel(
            name='GameAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_index', models.IntegerField()),
                ('choice_ids', models.JSONField(default=list)),
                ('is_correct', models.BooleanField(default=False)),
                ('response_ms', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='live.gameplayer')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='live.gamesession')),
            ],
        ),
        migrations.AddIndex(
            model_name='gamesession',
            index=models.Index(fields=['pin', 'status'], name='live_gamese_pin_76a0c1_idx'),
        ),
        migrations.AddConstraint(
            model_name='gameplayer',
            constraint=models.UniqueConstraint(fields=('session', 'nickname'), name='unique_nickname_per_game'),
        ),
        migrations.AddConstraint(
            model_name='gameanswer',
            constraint=models.UniqueConstraint(fields=('player', 'question_index'), name='unique_game_answer_per_question'),
        ),
    ]
