# Generated by Django 5.2.6 on 2026-08-23 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='status',
            field=models.CharField(choices=[('lobby', 'Lobby'), ('question', 'Question live'), ('reveal', 'Revealing answer'), ('scoreboard', 'Scoreboard interlude'), ('ended', 'Ended')], db_index=True, default='lobby', max_length=10),
        ),
    ]
