# Generated by Django 5.2.6 on 2026-08-23 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0002_alter_gamesession_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='scoreboard_every',
            field=models.PositiveSmallIntegerField(default=3, help_text='Show the scoreboard interlude after every N questions (1 = after each).'),
        ),
    ]
