# Generated by Django 5.2.6 on 2026-09-21

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0003_gamesession_scoreboard_every'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='gamesession',
            constraint=models.UniqueConstraint(
                condition=~models.Q(('status', 'ended')),
                fields=('pin',),
                name='unique_live_game_pin',
            ),
        ),
        migrations.RemoveConstraint(
            model_name='gameplayer',
            name='unique_nickname_per_game',
        ),
        migrations.AddConstraint(
            model_name='gameplayer',
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower('nickname'),
                models.F('session'),
                name='unique_nickname_per_game',
            ),
        ),
    ]
