# Generated by Django 5.2.6 on 2026-08-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_school_brand_color_school_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('premium', 'Premium')], db_index=True, default='free', max_length=20),
        ),
    ]
