# Generated by Django 5.2.6 on 2026-08-03 09:27

import cbtgen.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cbt', '0002_multi_answer_questions'),
        ('core', '0003_school_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIGenerationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.BooleanField(default=True, help_text='Master switch. Off blocks AI generation for every staff member.')),
                ('trial_limit', models.PositiveIntegerField(default=cbtgen.models.default_free_trials, help_text='How many successful generations a non-premium school gets before it is gated.')),
                ('trials_used', models.PositiveIntegerField(default=0)),
                ('disabled_staff', models.ManyToManyField(blank=True, help_text='Staff explicitly barred from AI generation while it is otherwise enabled.', related_name='ai_generation_disabled_in', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.school')),
            ],
            options={
                'verbose_name': 'AI generation settings',
                'verbose_name_plural': 'AI generation settings',
                'constraints': [models.UniqueConstraint(fields=('school',), name='one_ai_settings_per_school')],
            },
        ),
        migrations.CreateModel(
            name='QuestionGenerationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_level', models.CharField(max_length=30)),
                ('exam_standard', models.CharField(max_length=30)),
                ('subject_name', models.CharField(max_length=120)),
                ('topics', models.TextField(blank=True)),
                ('complexity', models.CharField(default='medium', max_length=10)),
                ('calculation_ratio', models.PositiveSmallIntegerField(default=0)),
                ('question_count', models.PositiveSmallIntegerField(default=10)),
                ('question_type', models.CharField(choices=[('single', 'Single answer'), ('multiple', 'Multiple answers')], default='single', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready for review'), ('failed', 'Failed'), ('committed', 'Saved to bank'), ('discarded', 'Discarded')], db_index=True, default='pending', max_length=20)),
                ('generated', models.JSONField(blank=True, default=list)),
                ('error', models.TextField(blank=True)),
                ('model_used', models.CharField(blank=True, max_length=60)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('committed_count', models.PositiveIntegerField(default=0)),
                ('committed_bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_jobs', to='cbt.questionbank')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_generation_jobs', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.school')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['school', 'status'], name='cbtgen_ques_school__fb1dce_idx'), models.Index(fields=['school', 'created_by'], name='cbtgen_ques_school__22458d_idx')],
            },
        ),
    ]
