# Generated by Django 5.2.6 on 2026-07-19 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('code', models.CharField(help_text='Short unique identifier used as a prefix for admission numbers.', max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school-logos/')),
                ('is_active', models.BooleanField(default=True, help_text='Deactivating a school immediately blocks all of its users from the API.')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
