# Generated by Django 5.2.6 on 2026-07-20 10:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='brand_color',
            field=models.CharField(default='#2563eb', help_text='Primary brand colour, applied across every account in this school.', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a hex colour such as #2563eb.', regex='^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$')]),
        ),
        migrations.AddField(
            model_name='school',
            name='display_name',
            field=models.CharField(blank=True, help_text='Optional short name shown in the sidebar instead of the full name.', max_length=120),
        ),
    ]
