# Generated by Django 5.2.6 on 2026-08-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='graduates_to',
            field=models.CharField(blank=True, help_text='Where these students go next, e.g. "Senior Secondary" or "Secondary school".', max_length=80),
        ),
        migrations.AddField(
            model_name='classroom',
            name='graduation_stage',
            field=models.CharField(choices=[('none', 'Not a graduating class'), ('level', 'Transitions to the next level'), ('school', 'Final class — graduates from school')], db_index=True, default='none', max_length=10),
        ),
    ]
