# Generated by Django 5.2.6 on 2026-09-24 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_classroom_graduates_to_classroom_graduation_stage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='graduates_to',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='graduation_stage',
        ),
    ]
