# Generated by Django 5.2.6 on 2026-07-19 17:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('instructions', models.TextField(blank=True)),
                ('question_count', models.PositiveIntegerField(help_text='How many questions to draw from the bank for each student.', validators=[django.core.validators.MinValueValidator(1)])),
                ('duration_minutes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('pass_mark_percent', models.PositiveSmallIntegerField(default=50)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('shuffle_questions', models.BooleanField(default=True)),
                ('shuffle_choices', models.BooleanField(default=True)),
                ('max_attempts', models.PositiveSmallIntegerField(default=1, help_text='Retakes are blocked once this many attempts are submitted.')),
                ('show_results_immediately', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed')], db_index=True, default='draft', max_length=20)),
                ('classrooms', models.ManyToManyField(blank=True, help_text='Classes eligible to sit this exam. Empty means the whole school.', related_name='exams', to='students.classroom')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams_created', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.school')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='students.academicsession')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='students.term')),
            ],
            options={
                'ordering': ['-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt_number', models.PositiveSmallIntegerField(default=1)),
                ('question_order', models.JSONField(default=list, help_text="Ordered list of Question ids forming this student's paper.")),
                ('choice_order', models.JSONField(blank=True, default=dict, help_text='Per-question choice ordering, keyed by question id.')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True, help_text='Server-authoritative deadline. Answers after this are rejected.')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('auto_submitted', 'Auto Submitted'), ('abandoned', 'Abandoned')], db_index=True, default='in_progress', max_length=20)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('total_marks', models.PositiveIntegerField(default=0)),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_passed', models.BooleanField(default=False)),
                ('auto_submit_task_id', models.CharField(blank=True, max_length=100)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='cbt.exam')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to='students.student')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='question-images/')),
                ('marks', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], db_index=True, default='medium', max_length=10)),
                ('explanation', models.TextField(blank=True, help_text='Shown to students after results are released.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions_created', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.school')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='cbt.question')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_banks_created', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.school')),
            ],
            options={
                'ordering': ['subject__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='cbt.questionbank'),
        ),
        migrations.AddField(
            model_name='exam',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='cbt.questionbank'),
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('marks_awarded', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('answered_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='cbt.examattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='cbt.question')),
                ('selected_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_answers', to='cbt.choice')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.school')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='questionbank',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_banks', to='cbt.subject'),
        ),
        migrations.AddField(
            model_name='exam',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='cbt.subject'),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['school', 'exam', 'status'], name='cbt_examatt_school__f58512_idx'),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['student', 'exam'], name='cbt_examatt_student_38c976_idx'),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['status', 'expires_at'], name='cbt_examatt_status_cb3149_idx'),
        ),
        migrations.AddConstraint(
            model_name='examattempt',
            constraint=models.UniqueConstraint(fields=('exam', 'student', 'attempt_number'), name='unique_attempt_number_per_student_per_exam'),
        ),
        migrations.AddIndex(
            model_name='choice',
            index=models.Index(fields=['question', 'is_correct'], name='cbt_choice_questio_a2ec7d_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['school', 'bank', 'is_active'], name='cbt_questio_school__76c7d4_idx'),
        ),
        migrations.AddIndex(
            model_name='studentanswer',
            index=models.Index(fields=['attempt', 'question'], name='cbt_student_attempt_6ba0ac_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentanswer',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='unique_answer_per_question'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_subject_name_per_school'),
        ),
        migrations.AddConstraint(
            model_name='questionbank',
            constraint=models.UniqueConstraint(fields=('school', 'subject', 'name'), name='unique_bank_name_per_subject'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['school', 'status'], name='cbt_exam_school__fd933e_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['school', 'starts_at', 'ends_at'], name='cbt_exam_school__659788_idx'),
        ),
    ]
