# Generated by Django 5.2.6 on 2026-07-19 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_teaching_role', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.school')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff_number', models.CharField(db_index=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('qualification', models.CharField(blank=True, max_length=200)),
                ('specialisation', models.CharField(blank=True, max_length=200)),
                ('date_employed', models.DateField(blank=True, null=True)),
                ('employment_status', models.CharField(choices=[('active', 'Active'), ('on_leave', 'On Leave'), ('resigned', 'Resigned')], db_index=True, default='active', max_length=20)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.school')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='staff.staffrole')),
            ],
            options={
                'verbose_name_plural': 'staff',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='TeacherClassAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_form_teacher', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='students.classroom')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.school')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='students.academicsession')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_assignments', to='staff.staff')),
                ('term', models.ForeignKey(blank=True, help_text='Leave blank for an assignment that spans the whole session.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='students.term')),
            ],
            options={
                'ordering': ['classroom__name', 'classroom__arm'],
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('audience', models.CharField(choices=[('all_staff', 'All Staff'), ('teachers', 'Teachers'), ('admins', 'Admins')], default='all_staff', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_completed', models.BooleanField(db_index=True, default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notices_created', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.school')),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Set to turn this notice into a pending assignment for one person.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_notices', to='staff.staff')),
            ],
            options={
                'ordering': ['is_completed', '-created_at'],
                'indexes': [models.Index(fields=['school', 'is_completed'], name='staff_notic_school__49f120_idx'), models.Index(fields=['school', 'assigned_to', 'is_completed'], name='staff_notic_school__f1e673_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='staffrole',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_staff_role_per_school'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['school', 'employment_status'], name='staff_staff_school__498721_idx'),
        ),
        migrations.AddConstraint(
            model_name='staff',
            constraint=models.UniqueConstraint(fields=('school', 'staff_number'), name='unique_staff_number_per_school'),
        ),
        migrations.AddIndex(
            model_name='teacherclassassignment',
            index=models.Index(fields=['school', 'teacher', 'is_active'], name='staff_teach_school__4d1ca7_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherclassassignment',
            index=models.Index(fields=['school', 'classroom', 'is_active'], name='staff_teach_school__622bda_idx'),
        ),
        migrations.AddConstraint(
            model_name='teacherclassassignment',
            constraint=models.UniqueConstraint(fields=('teacher', 'classroom', 'session', 'term'), name='unique_teacher_class_per_term'),
        ),
        migrations.AddConstraint(
            model_name='teacherclassassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_form_teacher', True)), fields=('classroom', 'session'), name='one_form_teacher_per_class_per_session'),
        ),
    ]
